title: Heather's William and Mary Classwork
description: This page will display classwork from my MSBA program at William and Mary.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
